Repository quantum-guy7/quantum-computation-notes, pull requests merged in 2020-10, with the labels that each got.

#2 add spin details, stern and gerlach experiment
  spins/Stern-Gerlach.png
  spins/spin_of_electron.md
Labels: hacktoberfest-accepted

#6 add entanglement introduction
  entanglement/entanglement-part-1.md
Labels: hacktoberfest, hacktoberfest-accepted

#7 update README - add impact of quantum computation
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#8 bell's inequality introduction added
  bells-inequality/bell.png
  bells-inequality/introduction.md
  bells-inequality/introduction_to_bell.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#11 added properties of vectors
  linear-algebra/properties.md
Labels: hacktoberfest, hacktoberfest-accepted
